### ISSUE TITLE
Consider putting addon up for adoption

### ISSUE THREAD

**Issue by pauln** [rhyek/ember-master-tab#5]
Hi there @rhyek,

> Sometimes an Ember addon needs a new maintainer. In order to make this a consolidated community effort, we started Adopted Ember Addons, an org where community members can find a new home for their ember addon.

It seems (from the lack of activity on this repo) as though you might not have the time/motivation to maintain this very useful addon any more.  If that's the case, could you please consider putting it up for adoption via the [Adopted Ember Addons program](https://github.com/adopted-ember-addons/program-guidelines)?

That way, the Ember community (including myself and @pabloascarza) can help maintain `ember-master-tab` and get new versions released so that it's readily available for use with the latest versions of Ember.

Cheers,
@pauln

**Comment by rhyek** [comment]
hi, @pauln. i'm very busy lately and am not sure about that adoption program. skimmed through it and it seems fine, but really would just rather add a maintainer to this repo and to npm.

**Comment by pauln** [comment]
Hi @rhyek, thanks for replying.

If there's somebody who you trust that's willing and able to be a maintainer, that'd be great.  If not, you're still able to be an author/maintainer after transferring it to the Adopted Ember Addons org - you don't have to entirely "give up" the addon, it's really just about making sure that there are other trusted people who have access to merge PRs and release new versions etc when you don't have time to.

If you're able to join the [Ember community](https://emberjs.com/community) Discord, there's an #adopted-ember-addons channel in which you can ask any other questions you might have about the process; the org owners are active there, and I'm sure they'll happily discuss it with you.

**Comment by pabloascarza** [comment]
Agree @pauln the adopted addons programs it's great and allow you to keep your addon up-to-date and keep the authoring on that, and it make posible for more people to use it. Ember is having great changes in this laters versions and it would be great that people can use this addon on these.

**Comment by rhyek** [comment]
what I mean is i don't have time at this moment to really look into any of this. if you guys can nominate someone to take over this project i will happily add them as maintainers to the repo and npm.

**Comment by pabloascarza** [comment]
Hi @rhyek as i really need it can you add me as maintaners. Thank you

**Comment by pabloascarza** [comment]
Hi @rhyek sory to ping you again, can you add me or other as mantainer so we can keep this add-on update. Thanks

**Comment by rhyek** [comment]
what is your npm username?

**Comment by pabloascarza** [comment]
Thank you for adding me!

**Comment by pabloascarza** [comment]
Sry my username is pabloascarza

**Comment by pauln** [comment]
@rhyek @pabloascarza Did you manage to get NPM access sorted out?  I see there are a couple of new versions tagged here on Github, but still not released on NPM.

**Comment by pabloascarza** [comment]
Sadly not yet :(

**Comment by rhyek** [comment]
@pabloascarza invited.

**Comment by pabloascarza** [comment]
1.3.0 published 😃
